### ISSUE TITLE
The map route could not be shown ever

### ISSUE THREAD

**Issue by laserdark** [Madmanmayson/BattleInfoPlugin#3]
Due to the updated version HTML5 [BLOCK-1], map route might be changed into another form. 
Now the function UpdateMapRank (line 104 in Master.cs) will throw an exception that key is not found in  dictionary. It seems that the method of building Data.json has failed.
I totally have no idea how to handle with this. Could you deal with it? thx a lot

**Comment by Madmanmayson** [comment]
I haven't played since the update to HTML yet so I haven't even tried combat yet either. I'll look into it tonight and see what is causing it.

**Comment by Madmanmayson** [comment]
I forgot BIP uses apistart2 as well for getting its initial data and that endpoint ended up changing to api_start2/getData so changing that in the Master.cs file fixed the issue. The change will be added in the next version of KCV but here is the dll for the fixed plugin.

[BattleInfoPlugin.zip](https://github.com/Madmanmayson/BattleInfoPlugin/files/2356375/BattleInfoPlugin.zip)
